export { default as store } from './store'
export { default as services } from './services'
export { default as routes } from './routes'
export { default as component } from './components/profile'
export { default as formUser } from './components/formUser'
export { default as page } from './pages/index'
