export const SET_SCROLL_WIDTH = 'MENU/SET_SCROLL_WIDTH'
export const SET_QUANTITY_PAGES = 'MENU/SET_QUANTITY_PAGES'
export const SET_PAGES = 'MENU/SET_QUANTITY_PAGES'
export const SET_CONTAINER_SIZE = 'MENU/SET_CONTAINER_SIZE'
