export const getNotations = ({ notations }) => notations
export const getLoading = ({ loading }) => loading
export const getFormDialog = ({ formDialog }) => formDialog
export const getFormEditMode = ({ formEditMode }) => formEditMode
export const getTable = ({ table }) => table
export const getTableCols = ({ table }) => table.cols
export const getTableRows = ({ table }) => table.rows
export const getTableFilter = ({ table }) => table.filter
export const getTableSelected = ({ table }) => table.selected
export const getForm = ({ form }) => form
export const getFormNotationId = ({ form }) => form.notation_id
export const getFormContractId = ({ form }) => form.contract_id
export const getFormTypeNotation = ({ form }) => form.type_notation
export const getFormReference = ({ form }) => form.reference
export const getFormEnter = ({ form }) => form.enter
export const getFormLeave = ({ form }) => form.leave
export const getFormNote = ({ form }) => form.note
