export const getContracts = ({ contracts }) => contracts
export const getLoading = ({ loading }) => loading
export const getForm = ({ form }) => form
export const getFormContractId = ({ form }) => form.contract_id
export const getFormClientId = ({ form }) => form.client_id
export const getFormServiceId = ({ form }) => form.service_id
export const getFormStartValidity = ({ form }) => form.start_validity
export const getFormEndValidity = ({ form }) => form.end_validity
export const getFormValue = ({ form }) => form.value
export const getFormTypeValue = ({ form }) => form.type_value
export const getFormDialog = ({ formDialog }) => formDialog
export const getOptions = ({ options }) => options
export const getFormDialogEditMode = ({ formDialogEditMode }) => formDialogEditMode
export const getContractShow = ({ contractShow }) => contractShow
export const getTableFilter = ({ tableFilter }) => tableFilter
