name: Publish Website to Web Hosting

on:
  push:
    branches: [ master ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 📃 Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          /.git/**/*
          /node_modules/**/*
          /.quasar/**/*
          /public/**/*
          /src/**/*
          /src-electron/**/*
          /src-pwa/**/*
          .editorconfig
          .eslintignore
          .eslintrc.js
          .gitignore
          .postcssrc.js
          babel.config.js
          jsconfig.json
          package.json
          quasar.config.js
          README.md
          yarn.lock
